<?php
/**
 * Site
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.1 (4.1)
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Site Class Doc Comment
 *
 * @category Class
 * @description Adds support for custom fields and tags.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Site implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Site';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'url' => 'string',
        'display_url' => 'string',
        'display' => 'string',
        'name' => 'string',
        'slug' => 'string',
        'status' => '\OpenAPI\Client\Model\LocationStatus',
        'region' => '\OpenAPI\Client\Model\BriefRegion',
        'group' => '\OpenAPI\Client\Model\BriefSiteGroup',
        'tenant' => '\OpenAPI\Client\Model\BriefTenant',
        'facility' => 'string',
        'time_zone' => 'string',
        'description' => 'string',
        'physical_address' => 'string',
        'shipping_address' => 'string',
        'latitude' => 'float',
        'longitude' => 'float',
        'comments' => 'string',
        'asns' => '\OpenAPI\Client\Model\ASN[]',
        'tags' => '\OpenAPI\Client\Model\NestedTag[]',
        'custom_fields' => 'array<string,mixed>',
        'created' => '\DateTime',
        'last_updated' => '\DateTime',
        'circuit_count' => 'int',
        'device_count' => 'int',
        'prefix_count' => 'int',
        'rack_count' => 'int',
        'virtualmachine_count' => 'int',
        'vlan_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'url' => 'uri',
        'display_url' => 'uri',
        'display' => null,
        'name' => null,
        'slug' => null,
        'status' => null,
        'region' => null,
        'group' => null,
        'tenant' => null,
        'facility' => null,
        'time_zone' => null,
        'description' => null,
        'physical_address' => null,
        'shipping_address' => null,
        'latitude' => 'double',
        'longitude' => 'double',
        'comments' => null,
        'asns' => null,
        'tags' => null,
        'custom_fields' => null,
        'created' => 'date-time',
        'last_updated' => 'date-time',
        'circuit_count' => 'int64',
        'device_count' => 'int64',
        'prefix_count' => 'int64',
        'rack_count' => 'int64',
        'virtualmachine_count' => 'int64',
        'vlan_count' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'url' => false,
        'display_url' => false,
        'display' => false,
        'name' => false,
        'slug' => false,
        'status' => false,
        'region' => true,
        'group' => true,
        'tenant' => true,
        'facility' => false,
        'time_zone' => true,
        'description' => false,
        'physical_address' => false,
        'shipping_address' => false,
        'latitude' => true,
        'longitude' => true,
        'comments' => false,
        'asns' => false,
        'tags' => false,
        'custom_fields' => false,
        'created' => true,
        'last_updated' => true,
        'circuit_count' => false,
        'device_count' => false,
        'prefix_count' => false,
        'rack_count' => false,
        'virtualmachine_count' => false,
        'vlan_count' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'url' => 'url',
        'display_url' => 'display_url',
        'display' => 'display',
        'name' => 'name',
        'slug' => 'slug',
        'status' => 'status',
        'region' => 'region',
        'group' => 'group',
        'tenant' => 'tenant',
        'facility' => 'facility',
        'time_zone' => 'time_zone',
        'description' => 'description',
        'physical_address' => 'physical_address',
        'shipping_address' => 'shipping_address',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'comments' => 'comments',
        'asns' => 'asns',
        'tags' => 'tags',
        'custom_fields' => 'custom_fields',
        'created' => 'created',
        'last_updated' => 'last_updated',
        'circuit_count' => 'circuit_count',
        'device_count' => 'device_count',
        'prefix_count' => 'prefix_count',
        'rack_count' => 'rack_count',
        'virtualmachine_count' => 'virtualmachine_count',
        'vlan_count' => 'vlan_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'url' => 'setUrl',
        'display_url' => 'setDisplayUrl',
        'display' => 'setDisplay',
        'name' => 'setName',
        'slug' => 'setSlug',
        'status' => 'setStatus',
        'region' => 'setRegion',
        'group' => 'setGroup',
        'tenant' => 'setTenant',
        'facility' => 'setFacility',
        'time_zone' => 'setTimeZone',
        'description' => 'setDescription',
        'physical_address' => 'setPhysicalAddress',
        'shipping_address' => 'setShippingAddress',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'comments' => 'setComments',
        'asns' => 'setAsns',
        'tags' => 'setTags',
        'custom_fields' => 'setCustomFields',
        'created' => 'setCreated',
        'last_updated' => 'setLastUpdated',
        'circuit_count' => 'setCircuitCount',
        'device_count' => 'setDeviceCount',
        'prefix_count' => 'setPrefixCount',
        'rack_count' => 'setRackCount',
        'virtualmachine_count' => 'setVirtualmachineCount',
        'vlan_count' => 'setVlanCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'url' => 'getUrl',
        'display_url' => 'getDisplayUrl',
        'display' => 'getDisplay',
        'name' => 'getName',
        'slug' => 'getSlug',
        'status' => 'getStatus',
        'region' => 'getRegion',
        'group' => 'getGroup',
        'tenant' => 'getTenant',
        'facility' => 'getFacility',
        'time_zone' => 'getTimeZone',
        'description' => 'getDescription',
        'physical_address' => 'getPhysicalAddress',
        'shipping_address' => 'getShippingAddress',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'comments' => 'getComments',
        'asns' => 'getAsns',
        'tags' => 'getTags',
        'custom_fields' => 'getCustomFields',
        'created' => 'getCreated',
        'last_updated' => 'getLastUpdated',
        'circuit_count' => 'getCircuitCount',
        'device_count' => 'getDeviceCount',
        'prefix_count' => 'getPrefixCount',
        'rack_count' => 'getRackCount',
        'virtualmachine_count' => 'getVirtualmachineCount',
        'vlan_count' => 'getVlanCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('display_url', $data ?? [], null);
        $this->setIfExists('display', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('group', $data ?? [], null);
        $this->setIfExists('tenant', $data ?? [], null);
        $this->setIfExists('facility', $data ?? [], null);
        $this->setIfExists('time_zone', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('physical_address', $data ?? [], null);
        $this->setIfExists('shipping_address', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('comments', $data ?? [], null);
        $this->setIfExists('asns', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('custom_fields', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('last_updated', $data ?? [], null);
        $this->setIfExists('circuit_count', $data ?? [], null);
        $this->setIfExists('device_count', $data ?? [], null);
        $this->setIfExists('prefix_count', $data ?? [], null);
        $this->setIfExists('rack_count', $data ?? [], null);
        $this->setIfExists('virtualmachine_count', $data ?? [], null);
        $this->setIfExists('vlan_count', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['display_url'] === null) {
            $invalidProperties[] = "'display_url' can't be null";
        }
        if ($this->container['display'] === null) {
            $invalidProperties[] = "'display' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 100)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 100.";
        }

        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ((mb_strlen($this->container['slug']) > 100)) {
            $invalidProperties[] = "invalid value for 'slug', the character length must be smaller than or equal to 100.";
        }

        if (!preg_match("/^[-a-zA-Z0-9_]+$/", $this->container['slug'])) {
            $invalidProperties[] = "invalid value for 'slug', must be conform to the pattern /^[-a-zA-Z0-9_]+$/.";
        }

        if (!is_null($this->container['facility']) && (mb_strlen($this->container['facility']) > 50)) {
            $invalidProperties[] = "invalid value for 'facility', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 200)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['physical_address']) && (mb_strlen($this->container['physical_address']) > 200)) {
            $invalidProperties[] = "invalid value for 'physical_address', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['shipping_address']) && (mb_strlen($this->container['shipping_address']) > 200)) {
            $invalidProperties[] = "invalid value for 'shipping_address', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['latitude']) && ($this->container['latitude'] >= 100)) {
            $invalidProperties[] = "invalid value for 'latitude', must be smaller than 100.";
        }

        if (!is_null($this->container['latitude']) && ($this->container['latitude'] <= -100)) {
            $invalidProperties[] = "invalid value for 'latitude', must be bigger than -100.";
        }

        if (!is_null($this->container['longitude']) && ($this->container['longitude'] >= 1000)) {
            $invalidProperties[] = "invalid value for 'longitude', must be smaller than 1000.";
        }

        if (!is_null($this->container['longitude']) && ($this->container['longitude'] <= -1000)) {
            $invalidProperties[] = "invalid value for 'longitude', must be bigger than -1000.";
        }

        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['last_updated'] === null) {
            $invalidProperties[] = "'last_updated' can't be null";
        }
        if ($this->container['circuit_count'] === null) {
            $invalidProperties[] = "'circuit_count' can't be null";
        }
        if ($this->container['device_count'] === null) {
            $invalidProperties[] = "'device_count' can't be null";
        }
        if ($this->container['prefix_count'] === null) {
            $invalidProperties[] = "'prefix_count' can't be null";
        }
        if ($this->container['rack_count'] === null) {
            $invalidProperties[] = "'rack_count' can't be null";
        }
        if ($this->container['virtualmachine_count'] === null) {
            $invalidProperties[] = "'virtualmachine_count' can't be null";
        }
        if ($this->container['vlan_count'] === null) {
            $invalidProperties[] = "'vlan_count' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets display_url
     *
     * @return string
     */
    public function getDisplayUrl()
    {
        return $this->container['display_url'];
    }

    /**
     * Sets display_url
     *
     * @param string $display_url display_url
     *
     * @return self
     */
    public function setDisplayUrl($display_url)
    {
        if (is_null($display_url)) {
            throw new \InvalidArgumentException('non-nullable display_url cannot be null');
        }
        $this->container['display_url'] = $display_url;

        return $this;
    }

    /**
     * Gets display
     *
     * @return string
     */
    public function getDisplay()
    {
        return $this->container['display'];
    }

    /**
     * Sets display
     *
     * @param string $display display
     *
     * @return self
     */
    public function setDisplay($display)
    {
        if (is_null($display)) {
            throw new \InvalidArgumentException('non-nullable display cannot be null');
        }
        $this->container['display'] = $display;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Full name of the site
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Site., must be smaller than or equal to 100.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug slug
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        if ((mb_strlen($slug) > 100)) {
            throw new \InvalidArgumentException('invalid length for $slug when calling Site., must be smaller than or equal to 100.');
        }
        if ((!preg_match("/^[-a-zA-Z0-9_]+$/", ObjectSerializer::toString($slug)))) {
            throw new \InvalidArgumentException("invalid value for \$slug when calling Site., must conform to the pattern /^[-a-zA-Z0-9_]+$/.");
        }

        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\LocationStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\LocationStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets region
     *
     * @return \OpenAPI\Client\Model\BriefRegion|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param \OpenAPI\Client\Model\BriefRegion|null $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            array_push($this->openAPINullablesSetToNull, 'region');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('region', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets group
     *
     * @return \OpenAPI\Client\Model\BriefSiteGroup|null
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param \OpenAPI\Client\Model\BriefSiteGroup|null $group group
     *
     * @return self
     */
    public function setGroup($group)
    {
        if (is_null($group)) {
            array_push($this->openAPINullablesSetToNull, 'group');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets tenant
     *
     * @return \OpenAPI\Client\Model\BriefTenant|null
     */
    public function getTenant()
    {
        return $this->container['tenant'];
    }

    /**
     * Sets tenant
     *
     * @param \OpenAPI\Client\Model\BriefTenant|null $tenant tenant
     *
     * @return self
     */
    public function setTenant($tenant)
    {
        if (is_null($tenant)) {
            array_push($this->openAPINullablesSetToNull, 'tenant');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant'] = $tenant;

        return $this;
    }

    /**
     * Gets facility
     *
     * @return string|null
     */
    public function getFacility()
    {
        return $this->container['facility'];
    }

    /**
     * Sets facility
     *
     * @param string|null $facility Local facility ID or description
     *
     * @return self
     */
    public function setFacility($facility)
    {
        if (is_null($facility)) {
            throw new \InvalidArgumentException('non-nullable facility cannot be null');
        }
        if ((mb_strlen($facility) > 50)) {
            throw new \InvalidArgumentException('invalid length for $facility when calling Site., must be smaller than or equal to 50.');
        }

        $this->container['facility'] = $facility;

        return $this;
    }

    /**
     * Gets time_zone
     *
     * @return string|null
     */
    public function getTimeZone()
    {
        return $this->container['time_zone'];
    }

    /**
     * Sets time_zone
     *
     * @param string|null $time_zone time_zone
     *
     * @return self
     */
    public function setTimeZone($time_zone)
    {
        if (is_null($time_zone)) {
            array_push($this->openAPINullablesSetToNull, 'time_zone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_zone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_zone'] = $time_zone;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 200)) {
            throw new \InvalidArgumentException('invalid length for $description when calling Site., must be smaller than or equal to 200.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets physical_address
     *
     * @return string|null
     */
    public function getPhysicalAddress()
    {
        return $this->container['physical_address'];
    }

    /**
     * Sets physical_address
     *
     * @param string|null $physical_address Physical location of the building
     *
     * @return self
     */
    public function setPhysicalAddress($physical_address)
    {
        if (is_null($physical_address)) {
            throw new \InvalidArgumentException('non-nullable physical_address cannot be null');
        }
        if ((mb_strlen($physical_address) > 200)) {
            throw new \InvalidArgumentException('invalid length for $physical_address when calling Site., must be smaller than or equal to 200.');
        }

        $this->container['physical_address'] = $physical_address;

        return $this;
    }

    /**
     * Gets shipping_address
     *
     * @return string|null
     */
    public function getShippingAddress()
    {
        return $this->container['shipping_address'];
    }

    /**
     * Sets shipping_address
     *
     * @param string|null $shipping_address If different from the physical address
     *
     * @return self
     */
    public function setShippingAddress($shipping_address)
    {
        if (is_null($shipping_address)) {
            throw new \InvalidArgumentException('non-nullable shipping_address cannot be null');
        }
        if ((mb_strlen($shipping_address) > 200)) {
            throw new \InvalidArgumentException('invalid length for $shipping_address when calling Site., must be smaller than or equal to 200.');
        }

        $this->container['shipping_address'] = $shipping_address;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude GPS coordinate in decimal format (xx.yyyyyy)
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            array_push($this->openAPINullablesSetToNull, 'latitude');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('latitude', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($latitude) && ($latitude >= 100)) {
            throw new \InvalidArgumentException('invalid value for $latitude when calling Site., must be smaller than 100.');
        }
        if (!is_null($latitude) && ($latitude <= -100)) {
            throw new \InvalidArgumentException('invalid value for $latitude when calling Site., must be bigger than -100.');
        }

        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude GPS coordinate in decimal format (xx.yyyyyy)
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            array_push($this->openAPINullablesSetToNull, 'longitude');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('longitude', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($longitude) && ($longitude >= 1000)) {
            throw new \InvalidArgumentException('invalid value for $longitude when calling Site., must be smaller than 1000.');
        }
        if (!is_null($longitude) && ($longitude <= -1000)) {
            throw new \InvalidArgumentException('invalid value for $longitude when calling Site., must be bigger than -1000.');
        }

        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets comments
     *
     * @return string|null
     */
    public function getComments()
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param string|null $comments comments
     *
     * @return self
     */
    public function setComments($comments)
    {
        if (is_null($comments)) {
            throw new \InvalidArgumentException('non-nullable comments cannot be null');
        }
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets asns
     *
     * @return \OpenAPI\Client\Model\ASN[]|null
     */
    public function getAsns()
    {
        return $this->container['asns'];
    }

    /**
     * Sets asns
     *
     * @param \OpenAPI\Client\Model\ASN[]|null $asns asns
     *
     * @return self
     */
    public function setAsns($asns)
    {
        if (is_null($asns)) {
            throw new \InvalidArgumentException('non-nullable asns cannot be null');
        }
        $this->container['asns'] = $asns;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \OpenAPI\Client\Model\NestedTag[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \OpenAPI\Client\Model\NestedTag[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return array<string,mixed>|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param array<string,mixed>|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        if (is_null($custom_fields)) {
            throw new \InvalidArgumentException('non-nullable custom_fields cannot be null');
        }
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created created
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            array_push($this->openAPINullablesSetToNull, 'created');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets last_updated
     *
     * @return \DateTime
     */
    public function getLastUpdated()
    {
        return $this->container['last_updated'];
    }

    /**
     * Sets last_updated
     *
     * @param \DateTime $last_updated last_updated
     *
     * @return self
     */
    public function setLastUpdated($last_updated)
    {
        if (is_null($last_updated)) {
            array_push($this->openAPINullablesSetToNull, 'last_updated');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_updated', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_updated'] = $last_updated;

        return $this;
    }

    /**
     * Gets circuit_count
     *
     * @return int
     */
    public function getCircuitCount()
    {
        return $this->container['circuit_count'];
    }

    /**
     * Sets circuit_count
     *
     * @param int $circuit_count circuit_count
     *
     * @return self
     */
    public function setCircuitCount($circuit_count)
    {
        if (is_null($circuit_count)) {
            throw new \InvalidArgumentException('non-nullable circuit_count cannot be null');
        }
        $this->container['circuit_count'] = $circuit_count;

        return $this;
    }

    /**
     * Gets device_count
     *
     * @return int
     */
    public function getDeviceCount()
    {
        return $this->container['device_count'];
    }

    /**
     * Sets device_count
     *
     * @param int $device_count device_count
     *
     * @return self
     */
    public function setDeviceCount($device_count)
    {
        if (is_null($device_count)) {
            throw new \InvalidArgumentException('non-nullable device_count cannot be null');
        }
        $this->container['device_count'] = $device_count;

        return $this;
    }

    /**
     * Gets prefix_count
     *
     * @return int
     */
    public function getPrefixCount()
    {
        return $this->container['prefix_count'];
    }

    /**
     * Sets prefix_count
     *
     * @param int $prefix_count prefix_count
     *
     * @return self
     */
    public function setPrefixCount($prefix_count)
    {
        if (is_null($prefix_count)) {
            throw new \InvalidArgumentException('non-nullable prefix_count cannot be null');
        }
        $this->container['prefix_count'] = $prefix_count;

        return $this;
    }

    /**
     * Gets rack_count
     *
     * @return int
     */
    public function getRackCount()
    {
        return $this->container['rack_count'];
    }

    /**
     * Sets rack_count
     *
     * @param int $rack_count rack_count
     *
     * @return self
     */
    public function setRackCount($rack_count)
    {
        if (is_null($rack_count)) {
            throw new \InvalidArgumentException('non-nullable rack_count cannot be null');
        }
        $this->container['rack_count'] = $rack_count;

        return $this;
    }

    /**
     * Gets virtualmachine_count
     *
     * @return int
     */
    public function getVirtualmachineCount()
    {
        return $this->container['virtualmachine_count'];
    }

    /**
     * Sets virtualmachine_count
     *
     * @param int $virtualmachine_count virtualmachine_count
     *
     * @return self
     */
    public function setVirtualmachineCount($virtualmachine_count)
    {
        if (is_null($virtualmachine_count)) {
            throw new \InvalidArgumentException('non-nullable virtualmachine_count cannot be null');
        }
        $this->container['virtualmachine_count'] = $virtualmachine_count;

        return $this;
    }

    /**
     * Gets vlan_count
     *
     * @return int
     */
    public function getVlanCount()
    {
        return $this->container['vlan_count'];
    }

    /**
     * Sets vlan_count
     *
     * @param int $vlan_count vlan_count
     *
     * @return self
     */
    public function setVlanCount($vlan_count)
    {
        if (is_null($vlan_count)) {
            throw new \InvalidArgumentException('non-nullable vlan_count cannot be null');
        }
        $this->container['vlan_count'] = $vlan_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


